### ISSUE TITLE
Datamatrix, code128 + text

### ISSUE THREAD

**Issue by getrav** [igorocampos/ESCPOS#14]
![4B63D4E9-AD5F-4156-9C1F-E0E764C65676](https://user-images.githubusercontent.com/62563577/83493565-edc47380-a482-11ea-9bce-a0fd581df270.png)

Does your code support datamatrix?
Can we print from NFC or Bluetooth?
I’m trying to create this label. I don’t understand the ESC/POS language well enough to code this.
LOT37575 is on both bar codes
TUSCAN-DENIM is text
Qty: 25.15 Yards is text

**Comment by igorocampos** [comment]
Hi there, 
I've tested the library with multiple bluetooth printer, no problems so far. Never had a NFC connection but my guess is it should be the same as BT and Ethernet.

About the label, this library can print QRCodes and Multiple types of BarCodes. I'm not sure whether barcode on the left of your label is QRCode or not, but the one on the right looks like Code128 (supported by this library).

Text is also pretty easy to print :)

**Comment by getrav** [comment]
It is datamatrix.  Can this tool print datamatrix 2D barcodes?
I am familiar with ZPL and I was able to write the ZPL language with the help of http://labelary.com/
Is there a similar tool for ESC/POS?

**Comment by igorocampos** [comment]
Oh, I just read the part you mentioned Datamatrix. Sorry.
Currently there's no command implemented to print those, and the manual I have (which is in this repo root) it doesn't mention it. That doesn't mean it can't be done, it could be a newer command than the manual itself. Here's the barcodes it mention:
![image](https://user-images.githubusercontent.com/10572656/83538581-5c79ef00-a4cc-11ea-8de0-b1bb2e308f48.png)
And then 2D Bar codes:
- QR Code
- PDF417

**Comment by igorocampos** [comment]
Here's what I found in a quicksearch:
![image](https://user-images.githubusercontent.com/10572656/83538874-b7134b00-a4cc-11ea-824d-c63c566b0470.png)
So I think it is possible, but needs implementation and testing. Is your hardware enabled to print Datamatrix with ESC POS?

**Comment by getrav** [comment]
The printer can print DataMatrix.
I don't know how to design the ESC/POS code but for ZPL it is like this:

^XA
^MMT
^PW477
^LL0203
^LS0
^FO5,10^BX,10,200
^FDLOT37575^FS
^BCN,100,Y,N,N
^FT180,0^A0N,34,33^FH\^FDLOT37575^FS
^FT180,151^A0N,34,31^FH\^FDTUSCAN-DENIM^FS
^FT160,188^A0N,34,33^FH\^FDQty:^FS
^FT229,188^A0N,34,33^FH\^FD25.15 Yards^FS
^XZ


Can you do something similar?

**Comment by igorocampos** [comment]
Yeah, I think so, I'll update the library based on the commands I found for Datamatrix (`GS Z`) and then you can test if it prints correctly, deal?

**Comment by getrav** [comment]
Hi Igor,
Did you get a chance to update the library?

**Comment by igorocampos** [comment]
I was wanting on your confirmation, but unfortunately, I did not have the time to do so, even if I wanted, sorry...

**Comment by igorocampos** [comment]
Another update:
It doesn't sound like EPSON supports this kind of printing... The screenshot I posted was actually from a  Shenzhen HCC Technology Co printer like POS80BSU model, and they have their own implementation of the QrCode (and other 2D Codes) which is not ESC Standard. That said, I'm closing this until someone can provide the regular ESC/POS (from EPSON) commands to print Datamatrix.
