### ISSUE TITLE
Is there a way to search for available printers without hard coding the address?

### ISSUE THREAD

**Issue by Omar-Belghaouti** [igorocampos/ESCPOS#17]
As the title suggests, I want to search for available printers in the PC so the address will be dynamic.

**Comment by igorocampos** [comment]
Hi Omar, currently it doesn't do that, but you are very much welcomed to do a Pull Request for it, and I'll gladly accept your feature :)

**Comment by Omar-Belghaouti** [comment]
@igorocampos Thanks, I will work on it!

**Comment by igorocampos** [comment]
Hey @Omar-Belghaouti just checking in, any updates on that?

**Comment by igorocampos** [comment]
No worries Omar, I totally get it. I'm gonna close the issue for now. If you ever wish to spare some fun time with that PR you can re-open it :)

Cheers
