### ISSUE TITLE
CodeTable for windows-1256

### ISSUE THREAD

**Issue by mRmEEeZ** [igorocampos/ESCPOS#20]
Hello,

can you please help me with code table for windows-1256

enum CodeTable already has Windows1252 with value of 16

what is the value of Windows1256 ?

Thanks

**Comment by igorocampos** [comment]
Hi @mRmEEeZ 
I googled it and it came up `Windows1256_ARABIC = 50` can you try that out? I no longer own a printer.

**Comment by igorocampos** [comment]
This is from EPSON [website](https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=1):
![image](https://user-images.githubusercontent.com/10572656/164262643-be9381f0-da09-452f-a1a8-5a11b1c4f2f8.png)
