### ISSUE TITLE
Impirmir en español

### ISSUE THREAD

**Issue by ChecksumUy** [igorocampos/ESCPOS#36]
Hello Igor. 

I am trying to print tickets with Spanish accents, for example, the word "address", instead of printing "ó" it prints strange characters.

I tried using "SelectInternationalCharacterSet(CharSet.SpainI)" but it doesn't work, what else can I try?

Saludos, Luis.

**Comment by igorocampos** [comment]
Hi! 
I believe you could try using the `SelectCodeTable` command, with the option `Windows1252` perhaps?

![image](https://github.com/igorocampos/ESCPOS/assets/10572656/785cb3d5-7d8d-466d-bfcb-f69fdb8509d4)

**Comment by ChecksumUy** [comment]
Hi Igor!
Thank you very much for your very quick response.

Honestly I still don't understand anything about these printers, I don't know how to send one bit or another, what I'm doing is this:

`byte[] bytesImpresion = LF;
                
bytesImpresion = bytesImpresion.Add(SelectInternationalCharacterSet(CharSet.LatinAmerica));`

I tried LatinAmerica, SpainI and SpainII

`bytesImpresion = bytesImpresion.Add(SelectCharSizeHeight(CharSizeHeight.Normal).Add(SelectJustification(Justification.Left), "COMENTARIO: "));

bytesImpresion = bytesImpresion.Add(SelectCharSizeHeight(CharSizeHeight.Normal).Add(SelectJustification(Justification.Left), pedido.ComentarioDireccion), LF);`

![image](https://github.com/igorocampos/ESCPOS/assets/106340666/73daff98-aba8-4756-8adf-4fe6a40b0cb2)
In that screenshot I wrote the words: "dirección" "compartió"



Likewise, I don't want to waste your time because I don't really have the knowledge to talk in depth about this type of printing. I thought it was appropriate to ask you to solve my problem and in case someone else needed help to be able to use this article.

Thanks a lot!

**Comment by igorocampos** [comment]
Right, but in addition to that, did you try using the SelectCodeTable command, with the option Windows1252 ?

**Comment by ChecksumUy** [comment]
Yes, I tried it but it didn't work either. Is the order in which the bytes are sent important?

`byte[] bytesImpresion = LF;

bytesImpresion = bytesImpresion.Add(SelectInternationalCharacterSet(CharSet.LatinAmerica),SelectCodeTable(CodeTable.Windows1252));`

**Comment by ChecksumUy** [comment]
Hi Igor!

I was able to solve the problem using the following code:

order.Comment.ToBytes(Encoding.GetEncoding("ISO-8859-1")

I was reviewing the documentation you wrote and that helped me solve it.

Thanks for your time!

**Comment by igorocampos** [comment]
I'm glad you figured it out.
